sudo: required

services:
  - docker

branches:
  only:
    - master
    - develop

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=wirnex/arguments-check.php
    - DOCKER_COMPOSE_VERSION=1.8.1
    - COMPOSE_INTERACTIVE_NO_CLI=1

before_install:
  - echo Before-Install-OK

before_script:
  - echo Before-Script-OK

script:
  - printenv
  - echo 'hello world'
  
notifications:
  email: never
  slack:

secure: "<TODO>"
